/**
 * Algod endpoint-specific Zod schemas for use with AlgorandPoller.
 *
 * These schemas are tailored for specific algod endpoints like getPendingTransactions
 * and combine the base endpoint schemas with transaction-level validators.
 *
 * @example
 * ```typescript
 * import { pendingPaymentWithNoteSchema } from '@algorandfoundation/algokit-utils/poller/schemas/algod'
 *
 * const poller = new AlgorandPoller(algorand)
 * await poller.start({
 *   endpoint: (algorand) => algorand.client.algod.getPendingTransactions({ max: 1000 }),
 *   query: pendingPaymentWithNoteSchema,
 *   timeout: { type: 'rounds', value: 100 },
 * })
 * ```
 */

export {
  anyPendingTransactionsSchema,
  basePendingTransactionsSchema,
  pendingPaymentBetweenAddressesSchema,
  pendingPaymentFromSenderSchema,
  pendingPaymentToReceiverSchema,
  pendingPaymentTransactionsSchema,
  pendingPaymentWithCloseOutFromSenderSchema,
  pendingPaymentWithCloseOutSchema,
  pendingPaymentWithCloseOutToAddressSchema,
  pendingPaymentWithMinAmountSchema,
  pendingPaymentWithNotePrefixSchema,
  pendingPaymentWithNoteSchema,
  pendingPaymentWithSpecificNoteSchema,
  pendingAssetClawbackSchema,
  pendingAssetTransferFromSenderSchema,
  pendingAssetTransferOfAssetSchema,
  pendingAssetTransferOfAssetToReceiverSchema,
  pendingAssetTransferToReceiverSchema,
  pendingAssetTransferTransactionsSchema,
  pendingAssetTransferWithCloseOutSchema,
  pendingAssetTransferWithMinAmountSchema,
  pendingAssetConfigByManagerSchema,
  pendingAssetConfigFromSenderSchema,
  pendingAssetConfigOfAssetSchema,
  pendingAssetConfigRemovingClawbackSchema,
  pendingAssetConfigRemovingFreezeSchema,
  pendingAssetConfigRemovingManagerSchema,
  pendingAssetConfigSettingClawbackSchema,
  pendingAssetConfigSettingFreezeSchema,
  pendingAssetConfigSettingManagerSchema,
  pendingAssetConfigSettingReserveSchema,
  pendingAssetConfigTransactionsSchema,
  pendingAssetConfigWithClawbackSchema,
  pendingAssetConfigWithFreezeSchema,
  pendingAssetConfigWithManagerSchema,
  pendingAssetCreationSchema,
  pendingAssetCreationWithNameSchema,
  pendingAssetCreationWithUnitNameSchema,
  pendingAssetDestroySchema,
  pendingAssetReconfigurationSchema,
  pendingAppCallFromSenderSchema,
  pendingAppCallToAppSchema,
  pendingAppCallToAppWithOnCompleteSchema,
  pendingAppCallTransactionsSchema,
  pendingAppCallWithAccountReferencesSchema,
  pendingAppCallWithAppReferencesSchema,
  pendingAppCallWithArgsSchema,
  pendingAppCallWithAssetReferencesSchema,
  pendingAppCallWithBoxReferencesSchema,
  pendingAppCallWithMinArgsSchema,
  pendingAppCallWithSpecificArgSchema,
  pendingAppClearStateSchema,
  pendingAppCloseOutSchema,
  pendingAppCreationSchema,
  pendingAppCreationWithBothStateSchemasSchema,
  pendingAppCreationWithExtraPagesSchema,
  pendingAppDeleteSchema,
  pendingAppNoOpSchema,
  pendingAppOptInSchema,
  pendingAppUpdateSchema,
  pendingKeyRegistrationTransactionsSchema,
  pendingOnlineKeyRegistrationSchema,
  pendingOfflineKeyRegistrationSchema,
  pendingKeyRegistrationWithVoteKeySchema,
  pendingKeyRegistrationWithSelectionKeySchema,
  pendingKeyRegistrationWithStateProofKeySchema,
  pendingKeyRegistrationFromSenderSchema,
  pendingOnlineKeyRegistrationFromSenderSchema,
  pendingOfflineKeyRegistrationFromSenderSchema,
  pendingKeyRegistrationWithVoteRangeSchema,
  pendingKeyRegistrationWithVoteDilationSchema,
  pendingKeyRegistrationFromSenderWithVoteRangeSchema,
  pendingAssetFreezeTransactionsSchema,
  pendingAssetFreezeSchema,
  pendingAssetUnfreezeSchema,
  pendingAssetFreezeFromSenderSchema,
  pendingAssetFreezeOfAssetSchema,
  pendingAssetFreezeTargetingSchema,
  pendingAssetFreezeOfAssetTargetingSchema,
  pendingAssetFreezeOfAssetTargetingWithStatusSchema,
  pendingAssetFreezeFromSenderOfAssetSchema
} from "./get-pending-transactions";
